source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '15.0'

target 'apm_ios_demo_swift' do
  use_frameworks!

  pod 'AlicloudApmAll', '2.2.0', :subspecs => [
    'AlicloudApmPerformance',
    'AlicloudApmRemoteLog',
    'AlicloudApmMemAlloc',
    'AlicloudApmMemLeak',
    'AlicloudApmMemLeakSwiftSupport'
  ]
end
