source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '13.0'

target 'apm_ios_demo' do
  use_frameworks!

  pod 'AlicloudApmAll' , '2.2.0', :subspecs => [
    'AlicloudApmPerformance',
    'AlicloudApmRemoteLog',
    'AlicloudApmMemAlloc',
    'AlicloudApmMemLeak'
  ]

end
